[features]
seeds = false
skip-lint = false

[programs.devnet]
tethics_registry = "BfyK1qYw59CPATaM4db7j9CLeaaJBbhsQTKfGtVdtpne"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
